### PR TITLE
Try macos-14

### PR DESCRIPTION
**Pull request by reznikmm**

### CODE REVIEW

**Comment by simonjwright** [comment]
Good to see you’ve jumped on this!

The process I used to run (see [my last cross-compilation script](https://github.com/simonjwright/building-gcc-macos-native/blob/ccce6a2bb6ceeb603f437617f3eeace6793daf4a/gcc.sh)) used an x86_64 base compiler (standard sources) to build a cross-compiler x86_64-x-aarch64 from iains’s sources, then to use that to build the native aarch64 compiler. I don’t do that now, because I already have an aarch64 compiler ([here’s one, if it’s useful](https://github.com/simonjwright/alire-index.mac/releases/tag/toolchain-13.2.1)).

The script above is a little outdated.

Please ignore the above if you’re well past this point!

I noticed that the build is using Xcode 15.0, which may well fail to link; and until we have GCC 14, Xcode 15.1 may result in misbehaving exception handling. See [my fix](https://github.com/simonjwright/xcode_15_fix).

**Comment by simonjwright** [comment]
I’ve always used `contrib/download_prerequisites` to install gmp &c sources with the compiler and build in-line. Avoids issues with which arch to use!

**Comment by reznikmm** [comment]
@simonjwright 
I guess Fabien will do the actual build, but I can't resist trying :)

**Comment by reznikmm** [comment]
@simonjwright Did you get something like this ? I've got this during linking of `gprbuild` :(
> ld: library not found for -lcrt0.o

**Comment by simonjwright** [comment]
I'm wondering whether it thinks it's built a cross-compiler? the "failed command" should have included `-lSystem"

**Comment by reznikmm** [comment]
I guess it's due to [gprbuild version bumb 22:0 -> 24:0](https://github.com/alire-project/GNAT-FSF-builds/commit/1af19fdea8321d34882c767801748a1228aeac4d). I've tried to build it on macos-12/x86_64 and it failed with the same error.

```sh
anod build gprbuild
cd .../aarch64-darwin/gprbuild/build; 
make TARGET=aarch64-apple-darwin23.2.0 prefix=... distall
gprbuild -p -m --target=aarch64-apple-darwin23.2.0 --relocate-build-tree -j0 -XBUILD=production\
  .../gprbuild.gpr -XLIBRARY_TYPE=static -XXMLADA_BUILD=static
base_gcc/install/bin/gcc gprbuild-main.o ...  -static ... -o .../gprbuild
```
GCC can't eat `-static` on Mac OS ([see this](https://stackoverflow.com/questions/5259249/creating-static-mac-os-x-c-build)).

**Comment by simonjwright** [comment]
I think it’s to do with gprbuild’s Makefile thinking it’s building in a cross- environment. See the 'Notes/Other sources' section in [this README](git@github.com:simonjwright/GNAT-FSF-builds.git) -- I’m not sure about the Xml/Ada changes, they don’t seem to have been needed.

I never reported these Makefile issues, but then the lack of response on [gprbuild issue #141](https://github.com/AdaCore/gprbuild/issues/141) isn’t encouraging. Still, may as well try ...

**Comment by simonjwright** [comment]
I just rebuilt GCC 13.2.0 & Gprbuild 24.0.0 without any of my patches and **there were no problems**.

Mind you, I used an [updated build script for GCC](https://github.com/simonjwright/building-gcc-macos-native/blob/main/gcc.sh) ...

**Comment by simonjwright** [comment]
I've just downloaded the build, and I see you're well ahead of me! Congratulations!

**Comment by reznikmm** [comment]
this was merged upstream :partying_face:

**Comment by simonjwright** [comment]
This is brilliant! Next, alire-index ...

**Comment by reznikmm** [comment]
Thank you Simon for your work! I've just merged your scripts into anod
specs. :) Well it took about 3 days , yeah...

чт, 14 бер. 2024, 13:56 користувач Simon Wright ***@***.***>
пише:

**Pull request closed without merging**
